# Generated by Django 5.2.6 on 2025-11-19 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_subject_unique_together_subject_departments_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("teacher_created", "Teacher Created"),
                            ("teacher_updated", "Teacher Updated"),
                            ("teacher_deleted", "Teacher Deleted"),
                            ("department_created", "Department Created"),
                            ("department_updated", "Department Updated"),
                            ("department_deleted", "Department Deleted"),
                            ("subject_created", "Subject Created"),
                            ("subject_updated", "Subject Updated"),
                            ("subject_deleted", "Subject Deleted"),
                            ("questionnaire_uploaded", "Questionnaire Uploaded"),
                            ("user_login", "User Login"),
                            ("system", "System Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activity_type", "created_at"],
                        name="accounts_ac_activit_0b5ba0_idx",
                    ),
                    models.Index(
                        fields=["is_read", "created_at"],
                        name="accounts_ac_is_read_463b47_idx",
                    ),
                ],
            },
        ),
    ]
