# Generated by Django 5.2.7 on 2026-03-01 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('teacher_created', 'Teacher Created'), ('teacher_updated', 'Teacher Updated'), ('teacher_deleted', 'Teacher Deleted'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('department_deleted', 'Department Deleted'), ('subject_created', 'Subject Created'), ('subject_updated', 'Subject Updated'), ('subject_deleted', 'Subject Deleted'), ('questionnaire_uploaded', 'Questionnaire Uploaded'), ('user_login', 'User Login'), ('system', 'System Activity'), ('subadmin_created', 'Sub-Admin Created'), ('subadmin_updated', 'Sub-Admin Updated'), ('subadmin_deleted', 'Sub-Admin Deleted')], max_length=50),
        ),
        migrations.CreateModel(
            name='SubAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subadmins', to=settings.AUTH_USER_MODEL)),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subadmin', to='accounts.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
