# Generated by Django 5.2.7 on 2026-04-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_is_archived_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('teacher_created', 'Teacher Created'), ('teacher_updated', 'Teacher Updated'), ('teacher_deleted', 'Teacher Deleted'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('department_deleted', 'Department Deleted'), ('subject_created', 'Subject Created'), ('subject_updated', 'Subject Updated'), ('subject_deleted', 'Subject Deleted'), ('program_created', 'Program Created'), ('program_updated', 'Program Updated'), ('program_deleted', 'Program Deleted'), ('questionnaire_uploaded', 'Questionnaire Uploaded'), ('user_login', 'User Login'), ('system', 'System Activity'), ('subadmin_created', 'Sub-Admin Created'), ('subadmin_updated', 'Sub-Admin Updated'), ('subadmin_deleted', 'Sub-Admin Deleted')], max_length=50),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.department')),
                ('subjects', models.ManyToManyField(blank=True, related_name='programs', to='accounts.subject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('code', 'department')},
            },
        ),
    ]
