# Generated by Django 5.2.7 on 2026-05-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teacherprofile_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='accounts.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='accounts.subject')),
            ],
            options={
                'verbose_name': 'Program Curriculum Entry',
                'verbose_name_plural': 'Program Curriculum Entries',
                'ordering': ['year_level', 'semester', 'subject__code'],
                'unique_together': {('program', 'subject')},
            },
        ),
    ]
