# Generated by Django 5.2.7 on 2026-05-11 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_programcurriculum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. CUR-001, BSCS-2024. Must be unique within the program.', max_length=50)),
                ('school_year', models.CharField(help_text='e.g. 2024-2025', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one curriculum per program should be active at a time.')),
                ('is_draft', models.BooleanField(default=True, help_text='Draft = still being edited. Saved = finalized (but editable until replaced).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curricula', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='accounts.program')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'ordering': ['-created_at'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='programcurriculum',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programcurriculum',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.curriculum'),
        ),
        migrations.AlterUniqueTogether(
            name='programcurriculum',
            unique_together={('curriculum', 'subject')},
        ),
    ]
