# Generated by Django 5.2.7 on 2026-05-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_curriculum_alter_programcurriculum_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
