# Generated by Django 5.2.16 on 2026-07-11 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_schoolyear_teachersubjectassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubjectassignment',
            options={'ordering': ['semester__school_year__name', 'semester__number', 'subject__code']},
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('is_current', models.BooleanField(default=False, help_text='Only one semester system-wide should be current at a time.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='accounts.schoolyear')),
            ],
            options={
                'ordering': ['school_year__name', 'number'],
                'unique_together': {('school_year', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together={('teacher', 'subject', 'semester')},
        ),
        migrations.RemoveField(
            model_name='teachersubjectassignment',
            name='school_year',
        ),
    ]
