# Generated by Django 5.2.16 on 2026-07-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_teachersubjectassignment_options_semester_and_more'),
    ]

    operations = [
    ]
