# Generated by Django 5.2.16 on 2026-07-11 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_backfill_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.semester'),
        ),
    ]
