# Generated by Django 5.2.7 on 2026-02-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questiontype_questionnaire_extraction_error_and_more'),
    ]

    operations = [
    ]
