# Generated by Django 5.2.7 on 2026-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_add_workspace_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='exam_type',
            field=models.CharField(choices=[('short_quiz', 'Short Quiz'), ('long_quiz', 'Long Quiz'), ('prelim', 'Prelim Exam'), ('midterm', 'Midterm Exam'), ('prefinal', 'Pre-Final Exam'), ('final', 'Final Exam'), ('activity', 'Activity / Seatwork'), ('others', 'Others')], default='others', help_text='Type of exam or test this questionnaire is intended for', max_length=20),
        ),
    ]
