# Generated by Django 5.2.7 on 2026-04-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_add_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='exam_type',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('semi_final', 'Semi-Final'), ('final', 'Final Term'), ('others', 'Others')], default='others', help_text='Academic term this questionnaire is intended for', max_length=20),
        ),
    ]
