# Generated by Django 5.2.7 on 2026-04-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_update_exam_type_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='school_year',
            field=models.CharField(blank=True, default='', help_text='School year (e.g. 2025-2026), auto-set on upload', max_length=9),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], default='', help_text='Semester when this questionnaire was uploaded', max_length=10),
        ),
    ]
