# Generated by Django 5.2.7 on 2026-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_workspacefolder_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='year_level',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Year level auto-detected from curriculum', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('short_quiz', 'Short Quiz'), ('long_quiz', 'Long Quiz'), ('prelim', 'Prelim'), ('semi_final', 'Semi-Final'), ('final_exam', 'Final Exam')], default='', help_text='Sub-category within the term (e.g. Short Quiz, Prelim)', max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('identification', 'Identification'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blanks'), ('matching', 'Matching Type'), ('enumeration', 'Enumeration')], max_length=50, unique=True),
        ),
    ]
