# Generated by Django 5.2.7 on 2026-05-16 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_curriculum_alter_programcurriculum_unique_together_and_more'),
        ('questionnaires', '0012_questionnaire_year_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='Curriculum version this questionnaire is tagged to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='accounts.curriculum'),
        ),
    ]
