# Generated by Django 5.2.7 on 2026-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_questionnaire_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('short_quiz', 'Short Quiz'), ('long_quiz', 'Long Quiz'), ('prelim', 'Prelim'), ('semi_final', 'Semi-Final'), ('midterm_exam', 'Midterm Exam'), ('final_exam', 'Final Exam')], default='', help_text='Sub-category within the term (e.g. Short Quiz, Prelim)', max_length=20),
        ),
    ]
